### ISSUE TITLE
"ReferenceError: React is not defined"

### ISSUE THREAD

**Issue by leopoldjoy** [unclecheese/react-selectable#8]
Hello,

Finally got react-selectable installed this morning, however now I'm getting an error that "React is not defined" when I try to run the application. Here's the error:

```
can't execute file: /pathToApp/bin/server.js
error given was: ReferenceError: React is not defined
    at Object.module.exports (/pathToApp/node_modules/react-selectable/dist/react-selectable.js:414:19)
    at __webpack_require__ (/pathToApp/node_modules/react-selectable/dist/react-selectable.js:21:30)
    at Object._interopRequire (/pathToApp/node_modules/react-selectable/dist/react-selectable.js:78:30)
    at __webpack_require__ (/pathToApp/node_modules/react-selectable/dist/react-selectable.js:21:30)
    at Object._interopRequire (/pathToApp/node_modules/react-selectable/dist/react-selectable.js:52:40)
    at __webpack_require__ (/pathToApp/node_modules/react-selectable/dist/react-selectable.js:21:30)
    at _interopRequire (/pathToApp/node_modules/react-selectable/dist/react-selectable.js:41:18)
    at Object.<anonymous> (/pathToApp/node_modules/react-selectable/dist/react-selectable.js:44:10)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at require.extensions.(anonymous function) (/pathToApp/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Object._module3.default._extensions.(anonymous function) [as .js] (/pathToApp/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:250:71)
further repeats of this error will be suppressed...
can't execute file: /pathToApp/bin/server.js
error given was: Error: File extension "jpeg" is already occupied by require-hacker
    at Object.extension (/pathToApp/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:342:10)
    at Object.hook (/pathToApp/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:202:12)
    at webpack_isomorphic_tools.register_extension (/pathToApp/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/index.js:304:47)
    at webpack_isomorphic_tools.register (/pathToApp/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/index.js:278:10)
    at webpack_isomorphic_tools.server (/pathToApp/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/index.js:182:8)
    at Object.<anonymous> (/pathToApp/bin/server.js:27:30)
    at Module._compile (module.js:413:34)
    at normalLoader (/pathToApp/node_modules/babel-core/lib/api/register/node.js:199:5)
    at require.extensions.(anonymous function) (/pathToApp/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Object._module3.default._extensions.(anonymous function) [as .js] (/pathToApp/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:250:71)
further repeats of this error will be suppressed...
(node) warning: possible EventEmitter memory leak detected. 11 disconnect listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:252:17)
    at process.once (events.js:278:8)
    at Worker.destroy (cluster.js:678:13)
    at Worker.__dirname.Worker.options.process.on.Worker.kill (cluster.js:47:16)
    at process.<anonymous> (/pathToApp/node_modules/piping/lib/launcher.js:49:27)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process._fatalException (node.js:256:26)
Hash: 4dcb6f472d28ae476097
Version: webpack 1.12.13
Time: 78744ms`
```

Any ideas what could be causing this?

**Comment by unclecheese** [comment]
Yeah, I'm getting the same thing. Working on it.

**Comment by leopoldjoy** [comment]
Awesome, thanks! Let me know if there's anything I can do to help.

**Comment by unclecheese** [comment]
Can you try again? `0.2.5` should resolve the issue.

**Comment by leopoldjoy** [comment]
That fixed it! Thanks so much!
